name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Seoul'
          timezoneMacos: 'Asia/Seoul'
          timezoneWindows: 'Seoul Standard Time'

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v3.1.1
      - run: npm install
      - run: npm run build
      - run: npm run export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
